"""modify table user

Revision ID: 387587f2876b
Revises: d8a3cb05dfc7
Create Date: 2023-03-23 13:09:07.000039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387587f2876b'
down_revision = 'd8a3cb05dfc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
