"""add new fields

Revision ID: 7e84c9a1dbe4
Revises: b6e703663a5f
Create Date: 2023-03-22 19:59:18.589109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e84c9a1dbe4'
down_revision = 'b6e703663a5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
