"""modify table user

Revision ID: 8a7d860f4f0f
Revises: bfa06b590665
Create Date: 2023-03-23 12:45:49.155777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7d860f4f0f'
down_revision = 'bfa06b590665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_photo_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'photo_id')
    op.drop_constraint('roles_user_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('roles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_user_id_fkey', 'roles', 'users', ['user_id'], ['id'])
    op.add_column('profiles', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_photo_id_fkey', 'profiles', 'profile_photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###
