"""remove relationhip profiles

Revision ID: 8c6f49c20e7c
Revises: 387587f2876b
Create Date: 2023-03-23 18:20:37.192502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6f49c20e7c'
down_revision = '387587f2876b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
