"""change fields

Revision ID: b6e703663a5f
Revises: bd91db2bdcd2
Create Date: 2023-03-21 23:55:37.121665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e703663a5f'
down_revision = 'bd91db2bdcd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
