"""add profilephoto table

Revision ID: bd91db2bdcd2
Revises: 7de95369c881
Create Date: 2023-03-21 22:58:30.563594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd91db2bdcd2'
down_revision = '7de95369c881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_photos_id'), 'profile_photos', ['id'], unique=False)
    op.add_column('profiles', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'profiles', 'profile_photos', ['photo_id'], ['id'])
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'last_name')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.add_column('profiles', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('profiles', 'photo_id')
    op.drop_index(op.f('ix_profile_photos_id'), table_name='profile_photos')
    op.drop_table('profile_photos')
    # ### end Alembic commands ###
