"""modify table user

Revision ID: d8a3cb05dfc7
Revises: 8a7d860f4f0f
Create Date: 2023-03-23 12:52:46.088737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a3cb05dfc7'
down_revision = '8a7d860f4f0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
