"""remove nullable

Revision ID: deb43ab44d1d
Revises: d57e81808262
Create Date: 2023-03-23 23:27:41.579773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb43ab44d1d'
down_revision = 'd57e81808262'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
